### ISSUE TITLE
Permission Denied (publickey)

### ISSUE THREAD

**Issue by theinsanitygames** [aco-rt/Foundry-VTT-Oracle#1]
Followed the video to the T, everything going super smoothly. Got to 21:00 to enter in the key, never came online. All I get is: my path, the ddns.net, and then this: 

Permission denied (publickey).

C:\Users\(mypcfilename)\Downloads>update
'update' is not recognized as an internal or external command,
operable program or batch file.

**Comment by aco-rt** [comment]
At 21 min in the video we are connecting to the server via ssh, you have downloaded the private key, which is what you use to connect, the one with the .key extension. You may be using the wrong key or a wrong type of key to connect. The other option is to use something like putty and point the program to the private key.

Only when the connection has been established, then one can use the linux (ubunbtu in this case) command to update the file list, here using 'sudo apt update'

If you are not able to connect, then you will have to try to connect to the instance first. If you are still having issues, let me know, and we can try to figure out what is causing the problem.
