### ISSUE TITLE
Script for Node is deprecated

### ISSUE THREAD

**Issue by urowak** [aco-rt/Foundry-VTT-Oracle#4]
Installation Scripts: The installation scripts setup_XX.x are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro.

https://github.com/nodesource/distributions#installation-instructions-1

**Comment by aco-rt** [comment]
Thank you for bringing this to my attention. I have updated the scripts to the recommended new method for ubuntu. I will be testing the scripts shortly to make sure it works.
