### ISSUE TITLE
Messed update from V10 how to fix issue or wipe and fresh install 

### ISSUE THREAD

**Issue by athos163** [aco-rt/Foundry-VTT-Oracle#6]
Hi Originally setup my server using your first script. When i went to update V11 during Christmas break, i went to manually do it but it didn't work so used your script but ended up with two instances of Foundry but can't access either. Not that experienced with this so wondered if there was an easy cmd to rectify. I already downloaded the files manually to backup and should still have the archive version, i wasn't sure if sudo rm -r / would be overkill or not and if there was an easier way to just uninstall and use your first script again?

![foundryissue](https://github.com/aco-rt/Foundry-VTT-Oracle/assets/151066665/dea1185a-77e2-46c8-af93-256694676ef1)

update

I've managed to remove the second instance, so only have one running but when i try node /home/ubuntu/foundry/resources/app/main.js --dataPath=/home/ubuntu/foundryuserdata to see if it's ok i get 

FoundryVTT | 2023-12-17 19:47:19 | [info] Running on Node.js - Version 20.10.0
FoundryVTT | 2023-12-17 19:47:19 | [info] Foundry Virtual Tabletop - Version 11 Build 315
FoundryVTT | 2023-12-17 19:47:19 | [info] User Data Directory - "/home/ubuntu/foundryuserdata"
FoundryVTT | 2023-12-17 19:47:19 | [info] Application Options:
{
  "compressStatic": true,
  "fullscreen": false,
  "hostname": "url to my host",
  "language": "en.core",
  "localHostname": null,
  "port": 443,
  "protocol": null,
  "proxyPort": 443,
  "proxySSL": true,
  "routePrefix": null,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "awsConfig": null,
  "compressSocket": true,
  "cssTheme": "foundry",
  "deleteNEDB": false,
  "hotReload": false,
  "passwordSalt": null,
  "sslCert": null,
  "sslKey": null,
  "world": null,
  "serviceConfig": null,
  "telemetry": false,
  "adminPassword": "•••••••••••••••••••••••••••••",
  "noBackups": false
}
FoundryVTT | 2023-12-17 19:47:19 | [info] Software license verification succeeded
FoundryVTT | 2023-12-17 19:47:19 | [error] Unable to start Express server: listen EACCES: permission denied 0.0.0.0:443
Error: Unable to start Express server: listen EACCES: permission denied 0.0.0.0:443
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at file:///home/ubuntu/foundry/resources/app/dist/server/express.mjs:1:6324
    at new Promise (<anonymous>)
    at Express.listen (file:///home/ubuntu/foundry/resources/app/dist/server/express.mjs:1:5992)
    at Module.initialize (file:///home/ubuntu/foundry/resources/app/dist/init.mjs:1:2008)

When i checked the options.json it only had /$vtturl by hostname so i switched it to my url but still the same. Looking at the script and host url it looked like it should be "my url (minus https)" i assumed the /$vtturl was to just pull through the hosturl when prompted or was that just the script telling it to place "my url/$vtturl" and thats what i'm missing the $vtturl at the end? 

Other than that i checked and it seems Caddy has listen for 443

**Comment by aco-rt** [comment]
https://github.com/aco-rt/Foundry-VTT-Oracle/blob/main/foundryUpdatev11.sh

Sorry somehow missed this message. I had made this script when this issue popped up. I am closing this as its solved in the above script.
